name: build-test-deploy_environments
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'starter/frontend/**'
  pull_request:
    branches: 
      - main
env:
  # Set Node.js Version
  NODE_VERSION: 'latest'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: "starter/frontend/package-lock.json"

    - name: Lint job
      run: |
        npm ci
        npm run lint
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: "starter/frontend/package-lock.json"

    - name: test job
      run: |
        npm ci
        npm run test
  build:
    needs: [lint, run-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: "starter/frontend/package-lock.json"

    - name: build job
      run: |
        npm ci
        npm run build --if-present
        npm run test